[project]
name = "pycrafter4500"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyusb>=1.2.1",
    "streamlit>=1.39.0",
]
